name             'perf_testing'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures perf_testing'
long_description 'Installs/Configures perf_testing'
version          '0.1.0'
depends          'build-essential'
